- src/main/java/com/alkemy/ong/model/entity/Activity.java
- src/main/java/com/alkemy/ong/repository/IActivityRepository.java
Entity and repository activity created
> Ot132 21: Crear modelo y repositorio base de Activities

- src/main/java/com/alkemy/ong/model/entity/Contact.java
- src/main/java/com/alkemy/ong/repository/IContactRepository.java
Added entity Contact with its repository.
> OT132-53: Create Contact's model and repository

- pom.xml
- src/main/java/com/alkemy/ong/model/entity/Organization.java
The entity was created with longbok Getter and Setter.
> OT132-15: create model and base repository of Organization

- src/main/java/com/alkemy/ong/seeder/ActivitySeeder.java
I test the seeder in my IDE and check it in MySQL Workbench making sure that the entities were created.
> Ot132-52: Create Seed Data to save existing Activities of the NGO

- pom.xml
- src/main/java/com/alkemy/ong/config/AWSConfiguration.java
- src/main/resources/application.properties
- src/main/resources/application.yaml
added the Amazon S3 file management service, through its SDK for Java and its dependency for future use to upload images.
> Ot132-38 Setup Amazon S3 SDK

- src/main/java/com/alkemy/ong/model/entity/Comment.java
This class needs the imports from classes "Users" and "News".
> OT132-74: model, repository and service creation for Comments

- src/main/java/com/alkemy/ong/mapper/OrganizationMapper.java
- src/main/java/com/alkemy/ong/mapper/SlideMapper.java
- src/main/java/com/alkemy/ong/model/response/OrganizationResponse.java
- src/main/java/com/alkemy/ong/model/response/SlideResponse.java
- src/main/java/com/alkemy/ong/service/OrganizationService.java
This ticket add the slides to the public endpoint sorted by the attribute "order". I attach an image with postman result. Although the image doesn't show all the slide list, it shows the first slides sort by order.
> OT132-60: Add slides to public endpoint

- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/mapper/MemberMapper.java
- src/main/java/com/alkemy/ong/model/request/CreateMemberRequest.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/abstraction/ICreateMember.java
Modified:
<ul>
<li>SecurityConfig</li>
<li>MemberController</li>
<li>MemberMapper</li>
<li>MemberService</li>
</ul>
Created:
<ul>
<li>CreateMemberRequest</li>
<li>ICreateMember</li>
</ul>
<h2>Postman</h2>
<h3>Success</h3>
<h3>Name error</h3>
<h3>Image error</h3>
<h3>Name + Image</h3>
> OT132-69: enpoint to create members

- etc/postman/OT132.postman_collection.json
This JSON is the one who has been shown in the demo today
> Postman JSON updated.

- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/AuthenticationController.java
- src/main/java/com/alkemy/ong/service/UserService.java
- src/main/java/com/alkemy/ong/service/abstraction/IGetUserDetails.java
Method /auth/me to get all the info about the currently logged user through JWT header
Images with examples (proof) of two different ways to do this tickets, one using spring security interface Principal and other using @RequestHeader.
> Ot132 36 Endponint authenticated user data

- README.md
- src/main/java/com/alkemy/ong/seeder/RoleSeeder.java
- src/main/java/com/alkemy/ong/seeder/UserSeeder.java
- src/main/java/com/alkemy/ong/service/RegisterService.java
* UserSeeder
* RoleSeeder
* README.md
> OT132-72: Create User Data Seed

- src/main/java/com/alkemy/ong/seeder/UserSeeder.java
Separated constants: names, lastnames, emails and password.
> OT132-Improved

- etc/postman/OT132.postman_collection.json
- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/repository/ISlideRepository.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/service/abstraction/IDeleteSlide.java
Slides deletion endpoint for revision. :)
> OT132-59: delete slide

- src/main/java/com/alkemy/ong/model/response/UserResponse.java
- src/main/java/com/alkemy/ong/service/RegisterService.java
> Ot132-49 Devolver token al usuario luego de registrarse en el sitio

- etc/postman/OT132.postman_collection.json
- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/mapper/TestimonialMapper.java
- src/main/java/com/alkemy/ong/model/request/UpdateTestimonialRequest.java
- src/main/java/com/alkemy/ong/service/TestimonialService.java
- src/main/java/com/alkemy/ong/service/abstraction/IUpdateTestimonial.java
Added put endpoint to TestimonialController.
* SecurityConfig
* TestimonialController
* TestimonialMapper
* TestimonialService
* IUpdateTestimonial
* UpdateTestimonialRequest
* #### Row 2 without changes
* #### Executed put over Row 2
* #### Row 2 updated
* #### Error to try to update with id 1
> OT132-66: Actualization's endpoint for Testimonials

- etc/postman/OT132.postman_collection.json
- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/SlideController.java
- src/main/java/com/alkemy/ong/mapper/SlideMapper.java
- src/main/java/com/alkemy/ong/model/response/SlideResponse.java
- src/main/java/com/alkemy/ong/service/SlideService.java
- src/main/java/com/alkemy/ong/service/abstraction/IGetSlideDetails.java
Resultado busqueda por ID
Error
> Ot132-56 Endpoint  Slides details

- pom.xml
- src/main/java/com/alkemy/ong/config/SwaggerConfig.java
- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/resources/application.properties
> OT132-84 add Swagger Documentation

- pom.xml
- src/main/java/com/alkemy/ong/common/mail/EmailUtils.java
- src/main/java/com/alkemy/ong/service/RegisterService.java
- src/main/resources/application.properties
- src/test/java/com/alkemy/ong/integration/user/RegisterUserIntegrationTest.java
Respuesta 202 al crear el user
Correo recibido de sendgrid
> OT132-30 Welcome email sending

- etc/postman/OT132.postman_collection.json
- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/CommentController.java
- src/main/java/com/alkemy/ong/mapper/CommentMapper.java
- src/main/java/com/alkemy/ong/model/request/CreateCommentRequest.java
- src/main/java/com/alkemy/ong/service/CommentService.java
- src/main/java/com/alkemy/ong/service/abstraction/ICreateComment.java
> Ot132 76: "Creación de comentarios"

- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/ActivityController.java
- src/main/java/com/alkemy/ong/model/request/UpdateActivityRequest.java
- src/main/java/com/alkemy/ong/repository/IActivityRepository.java
- src/main/java/com/alkemy/ong/service/ActivityService.java
- src/main/java/com/alkemy/ong/service/abstraction/IUpdateActivity.java
Update activity using http method PUT.
1- Existing entries in data base
2- modification successful
3- id not found
> OT132-51 Update Activity

- etc/postman/OT132.postman_collection.json
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/model/response/ListMembersResponse.java
- src/main/java/com/alkemy/ong/model/response/MemberResponse.java
- src/main/java/com/alkemy/ong/repository/IMemberRepository.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/abstraction/IGetMemberDetails.java
This ticket add the pagination to the member list. In the following images there is an example of showing the first page with 10 members per page.
If we go to the headers response we can see a link to the next page:
In the second page the links allow to go to the previous page or to the next page:
And in the last page, only allow to go the previous page:
> OT132-82: Add pagination to Members

- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/model/request/UpdateMemberRequest.java
- src/main/java/com/alkemy/ong/repository/IMemberRepository.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/abstraction/IUpdateMember.java
Added update endpoint to MemberController.
- SecurityConfig
- MemberController
- IMemberRepository
- MemberService
- IUpdateMember
- UpdateMemberRequest
- #### Row 1 without changes
- #### Executed update over Row 1
- #### Row 1 changed
- #### Error to try to update with id 0
> OT132-71: Actualization's endpoint for Members

- etc/postman/OT132.postman_collection.json
- src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/service/MemberService.java
- src/main/java/com/alkemy/ong/service/abstraction/IDeleteMember.java
Magui, revisé y no veo conflicts aqui en GitHub. De todas formas, previamente hice lo siguiente (corregime, pq no recuerdo si era así como me dijiste): 
Paso 1: hago el commit de mi rama
Paso 2: me voy a la main, hago pull.
Paso 3: git merge miRama
Paso 4: parado en main, verifico que no haya conflictos.
Y acá es donde tengo las dudas (pq ahora no me apareció ningún conflicto)
¿Tengo que corregir parado en este nuevo main mergeado y luego hacer un push desde el main mergeado y ya corregido?
Por otro lado, no se si es buena práctica lo que hice con el archivo de Postman Collection (reemplacé el archivo por el que yo actualicé y descargué).
Saludos! :)
> OT132-70: Members delete endpoint

- src/main/java/com/alkemy/ong/config/SwaggerConfig.java
- src/main/java/com/alkemy/ong/controller/MemberController.java
- src/main/java/com/alkemy/ong/controller/TestimonialController.java
- src/main/java/com/alkemy/ong/model/request/CreateMemberRequest.java
- src/main/java/com/alkemy/ong/model/request/UpdateMemberRequest.java
- src/main/java/com/alkemy/ong/model/response/MemberResponse.java
This add documentation to the member's endpoint.
Get:
Post:
Put:
Delete:
> OT132-87: Add Member's documentation

- etc/postman/OT132.postman_collection.json
Added Comment Put Request to Postman
> OT132-Update: Postman Collection
